// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaztgvAQSYSyOwCEHJOBi6tl_LTuzT_E4',
    appId: '1:509282603787:web:fa9691a140723acf32c80e',
    messagingSenderId: '509282603787',
    projectId: 'qr-yoklama-sistemi-e9f4e',
    authDomain: 'qr-yoklama-sistemi-e9f4e.firebaseapp.com',
    databaseURL: 'https://qr-yoklama-sistemi-e9f4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qr-yoklama-sistemi-e9f4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKJ7swDd1OM5B-13_-yovALKLRlGKbr0',
    appId: '1:509282603787:android:560439508f6a5c0e32c80e',
    messagingSenderId: '509282603787',
    projectId: 'qr-yoklama-sistemi-e9f4e',
    databaseURL: 'https://qr-yoklama-sistemi-e9f4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qr-yoklama-sistemi-e9f4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmR4ooAw7IGDtV3Dr2rvFogPJETU-KFp8',
    appId: '1:509282603787:ios:e791b3ee6b0d949432c80e',
    messagingSenderId: '509282603787',
    projectId: 'qr-yoklama-sistemi-e9f4e',
    databaseURL: 'https://qr-yoklama-sistemi-e9f4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qr-yoklama-sistemi-e9f4e.firebasestorage.app',
    iosBundleId: 'com.metinalptekin.yoklama.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmR4ooAw7IGDtV3Dr2rvFogPJETU-KFp8',
    appId: '1:509282603787:ios:e791b3ee6b0d949432c80e',
    messagingSenderId: '509282603787',
    projectId: 'qr-yoklama-sistemi-e9f4e',
    databaseURL: 'https://qr-yoklama-sistemi-e9f4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qr-yoklama-sistemi-e9f4e.firebasestorage.app',
    iosBundleId: 'com.metinalptekin.yoklama.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaztgvAQSYSyOwCEHJOBi6tl_LTuzT_E4',
    appId: '1:509282603787:web:ddce1d39bcba307f32c80e',
    messagingSenderId: '509282603787',
    projectId: 'qr-yoklama-sistemi-e9f4e',
    authDomain: 'qr-yoklama-sistemi-e9f4e.firebaseapp.com',
    databaseURL: 'https://qr-yoklama-sistemi-e9f4e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'qr-yoklama-sistemi-e9f4e.firebasestorage.app',
  );
}
